### ISSUE TITLE
Cannot import md3 models in blender 2.78

### ISSUE THREAD

**Issue by bassmaster429** [neumond/blender-md3#5] opened 2017-03-01 21:58 UTC
Cannot import md3 models in blender 2.78. Can someone help?

**Comment by neumond** [comment] 2017-03-02 03:07
@bassmaster429 Can you describe your problem?

**Comment by neumond** [comment] 2017-07-08 17:37
I guess this is a duplicate of #4, closing.

**Closed by neumond** 2017-07-08 17:37 UTC
